Add DUCTS to project list.
MakeContributions/ideahub pull request #109
Opened 2022-10-03 17:57 UTC by ATREAY

2022-10-04 16:23 UTC, ATREAY commented
> @ATREAY you need to add your project details to two files [ideas.json](https://github.com/MakeContributions/ideahub/edit/main/data/ideas.json) or [projects.json](https://github.com/MakeContributions/ideahub/edit/main/data/projects.json)
> 
> Please read [Contributing Guidelines](https://github.com/MakeContributions/ideahub#contribution-guidelines)

I added my project details in projects.json file.
or is it like I need to add details in both the files.

2022-10-04 16:36 UTC, AryanP45 commented
> > @ATREAY you need to add your project details to two files [ideas.json](https://github.com/MakeContributions/ideahub/edit/main/data/ideas.json) or [projects.json](https://github.com/MakeContributions/ideahub/edit/main/data/projects.json)
> > Please read [Contributing Guidelines](https://github.com/MakeContributions/ideahub#contribution-guidelines)
> 
> I added my project details in projects.json file. or is it like I need to add details in both the files.

both files Please read [Contributing Guidelines](https://github.com/MakeContributions/ideahub#contribution-guidelines)

2022-10-04 17:19 UTC, AryanP45 requested changes
name should be Repository's name on github 
and display should me title

2022-10-04 17:19 UTC, AryanP45 commented on data/projects.json
> +        "description": "This software is designed for the NCB to track the supply chain of chemicals that can be illicitly used from the manufacturer to the end-user.",
```
"name": "DUCTS",
"display": "Dual Use Chemical Tracking System",
```

2022-10-04 17:37 UTC, AryanP45 approved these changes

2022-10-04 18:19 UTC, AryanP45 commented
LGTM

2022-10-05 16:42 UTC, ATREAY commented
Any Updates??

2022-10-06 00:31 UTC, ming-tsai approved these changes

2022-10-06 00:31 UTC, merged