Add project Copia Backups to projects.json
MakeContributions/ideahub pull request #124
Opened 2022-10-13 11:25 UTC by lmponcio

2022-10-13 12:46 UTC, ming-tsai requested changes
Hi @lmponcio,
Could you please add the idea to the `ideas.json`?

> Make should that the first tag of the idea should have the tag `copia-backups` and add the tag on the proejct

2022-10-14 00:36 UTC, lmponcio commented
Hi @ming-tsai 
Thanks for your instructions :)

I have just pushed the requested changes in a new commit.
This is my first time adding changes after receiving a review comment so I hope I did it the right way. If I did something wrong please let me know and I'll start from scratch

Thanks again, regards

2022-10-16 00:55 UTC, ming-tsai commented on data/projects.json
> +        "tags": "python, backups, scripting"
```suggestion
        "tags": "python, copia-backups, scripting"
```

2022-10-16 00:55 UTC, ming-tsai approved these changes

2022-10-16 00:58 UTC, merged