Add my projects to the hub
MakeContributions/ideahub pull request #69
Opened 2022-03-20 04:51 UTC by sahilpatel09

I have 2 projects built on top of Vue js and thought can be useful for someone to learn from it.

2022-03-21 12:51 UTC, ming-tsai requested changes
Hi @sahilpatel09,
Please check the below suggestion.

2022-03-21 12:51 UTC, ming-tsai commented on data/projects.json
> +        "tags": "vuejs, personal site, Gridsome, Graphql, markdown, personal blog"
```suggestion
        "tags": "vuejs, personal-website, Gridsome, Graphql, markdown, personal-blog"
```

2022-03-21 16:04 UTC, sahilpatel09 reviewed
Updated with the suggestions.

2022-03-23 13:04 UTC, ming-tsai approved these changes

2022-03-23 13:04 UTC, merged