Fix typos
MakeContributions/ideahub pull request #80
Opened 2022-06-25 06:19 UTC by deesclouds

2022-06-26 01:07 UTC, ming-tsai requested changes
Hi @deesclouds,
I added some suggestions for the pr.

2022-06-26 01:07 UTC, ming-tsai commented on data/ideas.json
> +        "tags": "tetris,game, classic"
Add space before `game`
```suggestion
        "tags": "tetris, game, classic"
```

2022-06-26 01:07 UTC, ming-tsai commented on data/projects.json
> +        "name": "Memory-Card-Game",
Rollback this change due to the repository name is `Memoy-Card-Game`
```suggestion
        "name": "Memoy-Card-Game",
```

2022-06-26 05:02 UTC, deesclouds reviewed
agree with changes for spacing and name issue

2022-06-29 21:04 UTC, ming-tsai approved these changes

2022-08-28 21:25 UTC, ming-tsai requested changes

2022-08-28 21:25 UTC, ming-tsai commented on data/ideas.json
> +        "level": "beginner, intermediate",
```suggestion
        "level": "intermediate",
```

2022-08-28 21:28 UTC, ming-tsai commented on data/projects.json
> +        "level": "basic, intermediate",
```suggestion
        "level": "intermediate",
```

2022-08-28 21:34 UTC, ming-tsai approved these changes

2022-08-28 21:34 UTC, merged