Clash of Space game both Idea and Project added
MakeContributions/ideahub pull request #94
Opened 2022-09-09 12:28 UTC by Rajspeaks

Clash of Space game both Idea and Project added

2022-09-09 20:12 UTC, ming-tsai requested changes
Hi @Rajspeaks,
Some suggestions for the pull request.

2022-09-09 20:12 UTC, ming-tsai commented on data/ideas.json
> +        "tags": "clas-of-space, game, spacewar, alien-shooting, action"
Please separate the word using the dash(`-`)
```suggestion
        "tags": "clash-of-space, game, space-war, alien-shooting, action"
```

2022-09-09 20:12 UTC, ming-tsai commented on data/projects.json
> +        "tags": "game, html, css, javascript, space"
To a match the project to a idea please add the first tag of the idea, in this case
```suggestion
        "tags": "game, html, css, javascript, space, clash-of-space"
```

2022-09-09 20:12 UTC, ming-tsai commented on data/ideas.json
>      }
Please add an missing `,`

2022-09-09 20:12 UTC, ming-tsai commented on data/projects.json
>      }
Please add an missing `,`

2022-09-10 10:21 UTC, Rajspeaks reviewed
Changes done

2022-09-10 10:22 UTC, Rajspeaks commented on data/ideas.json
>      }
I have added the requirements

2022-09-10 10:23 UTC, Rajspeaks commented on data/projects.json
>      }
Added

2022-09-11 19:39 UTC, ming-tsai approved these changes

2022-09-11 19:40 UTC, ming-tsai approved these changes

2022-09-11 19:44 UTC, merged