add new project idea
MakeContributions/ideahub pull request #95
Opened 2022-09-10 03:26 UTC by MahendraBishnoi29

2022-09-10 06:54 UTC, MahendraBishnoi29 commented
@ming-tsai review my PR please.

2022-09-11 19:37 UTC, ming-tsai requested changes
Hi @MahendraBishnoi29,
Some suggestions for the pull request.

2022-09-11 19:37 UTC, ming-tsai commented on data/ideas.json
> +        "tags": "api, react"
- The first tag is used to match projects with an idea, so please add the book-app tag
- Remove the programming tag, due to is only an idea so the everyone could make on whatever programming language
```suggestion
        "tags": "picture-finder, api"
```

2022-09-11 19:38 UTC, ming-tsai requested changes

2022-09-11 19:38 UTC, ming-tsai commented on data/ideas.json
> +        "level": "beginner",
The level should be one of this list  `basic, intermediate, advanced`
```suggestion
        "level": "basic",
```

2022-09-14 20:45 UTC, ming-tsai approved these changes

2022-09-14 20:45 UTC, merged